[package]
name = "lndir"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]

[[test]]
name = "cucumber"
harness = false # Allows Cucumber to print output instead of libtest

[dev-dependencies]
cucumber_rust = "0.3.3"
regex = "1"
mktemp = "0.3.1"
